# Generated by Django 5.2.13 on 2026-04-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0003_alter_routinetask_options_routinetask_order_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NightReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day", models.DateField(db_index=True)),
                ("wins", models.TextField(blank=True)),
                ("energy", models.PositiveSmallIntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="night_reviews", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-day", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="NightReviewItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("outcome", models.CharField(choices=[("done", "Done"), ("slipped", "Slipped")], max_length=16)),
                ("reason", models.CharField(blank=True, max_length=280)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("review", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="planning.nightreview")),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="night_review_items", to="tasks.task")),
            ],
            options={
                "ordering": ["task_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="nightreview",
            constraint=models.UniqueConstraint(fields=("user", "day"), name="unique_user_night_review_day"),
        ),
        migrations.AddConstraint(
            model_name="nightreviewitem",
            constraint=models.UniqueConstraint(fields=("review", "task"), name="unique_night_review_item_task"),
        ),
    ]
