# Generated by Django 5.2.13 on 2026-04-24 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutineCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_checks', to=settings.AUTH_USER_MODEL)),
                ('routine_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='tasks.routinetask')),
            ],
            options={
                'ordering': ['-day', 'routine_task_id'],
                'indexes': [models.Index(fields=['user', 'day'], name='tasks_routi_user_id_1ccf5e_idx')],
                'constraints': [models.UniqueConstraint(fields=('routine_task', 'day'), name='unique_routine_task_day')],
            },
        ),
    ]
