# Generated by Django 5.2.13 on 2026-04-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_routinetask_routinecheck'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routinetask',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='routinetask',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='routinetask',
            name='routine_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
